### ISSUE TITLE
Rate Limiter and Return Download Option

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#1]
Hey, great project.
Could you add a rate limiter? The programm throws errors once its rate limited from mangadex site and cant verify the pictures for the zip compression anymore.

Also a return download option would be great. E.g safe somewhere to which chapter and picture the downlaod has porgressed and then, if you run the script again it picks up where it left of...This is also helpfull for updating an existing download of your mangacollection.

And finaly how about integrating a image decrypter for MangaPlus links?

**Comment by Sydiepus** [comment]
hello, sorry for the inconvenience, it should be fixed now.    
![image](https://user-images.githubusercontent.com/49863809/131197945-3e8c0484-58ef-4c89-9afa-0317e0440691.png)

**Comment by linus727** [comment]
Hey, there seems to be another error. After some chapters it threw this error:
![grafik](https://user-images.githubusercontent.com/61510392/131218973-7616f909-2301-408f-aee4-6925bc5e0584.png)

Is it trying to recheck pictures that are already zipped and deleted? I tried with the following mangadex id https://mangadex.org/title/1389d660-b9b1-4c6a-81af-eab4dbf3f22b

**Comment by Sydiepus** [comment]
Here it's trying to fix the zip file because it detected that there's some missing pages.    It seems like a bug (probably me).   
I'm working on it.  
Thank you for reporting.

**Comment by Sydiepus** [comment]
It should be fixed.  
Sorry again and thank you for helping me out.

**Comment by linus727** [comment]
Hey, I'm sorry, but I'm still getting the same error with the updated version. It only downloads 6 pictures, but the zip file expects 9? I saw this error on booth mangas I tried.
![grafik](https://user-images.githubusercontent.com/61510392/131228508-8acfb4a1-c98d-43b9-83cb-49f5ae8c5070.png)

**Comment by Sydiepus** [comment]
Weird i'll look into the issue gimme sometime.

**Comment by Sydiepus** [comment]
ohh my bad the issue is the dot in the chapter name i'll fix right away.

**Comment by Sydiepus** [comment]
it should be fixed i suppose.

**Comment by linus727** [comment]
It's working now! Great work.
I have another suggestion, there is some weird behavior when for one chapter two translation groups exist. It's trying to add additional images to the already existing zipfiles from the other translation group, in which case the picture order won't make any sense. Maybe a solution would be to add the translation group in brackets behind the chapter count.

**Comment by linus727** [comment]
I just found this bug where it downloads in bulk download the same chapters from the first manga and doesn't switch to the next one in the list after it finished it. So it will save the chapter from the first manga as the next one in line. See in the images that the file size is the exact same form different mangas. I also confirmed the pictures inside where the same and not from the actual manga that the folder is for.
![grafik](https://user-images.githubusercontent.com/61510392/131231020-9e8615db-b804-449c-993d-947e3144989f.png)

**Comment by Sydiepus** [comment]
> It's working now! Great work.
> I have another suggestion, there is some weird behavior when for one chapter two translation groups exist. It's trying to add additional images to the already existing zipfiles from the other translation group, in which case the picture order won't make any sense. Maybe a solution would be to add the translation group in brackets behind the chapter count.

can you me show the contents of one the zip files which contains the images from 2 translation group ?

**Comment by Sydiepus** [comment]
> e images that the file size

how odd could be the new chapter fetch that caused this issue i'll on it.

**Comment by Sydiepus** [comment]
i'll close this issue and create a separate one for the bulk download bug and another for the 2 translation.
